### ISSUE TITLE
Schema Values List not same

### ISSUE THREAD

**Issue by beautybird** [getsynth/synth#9] opened 2021-06-08 22:36 UTC
Hi,
I created a schema with 11 fields of different types.
The PG table consist of  a serial field + 11 fields with same names and types as the schema .

Now when I try generate to the postgres :
synth generate  --collection test_data  --to postgres://admin:1122@localhost:5432/data   ~/db_test/data/

I get the error as mentioned below : -
Caused by:
    0: db error: ERROR: VALUES lists must all be the same length
    1: ERROR: VALUES lists must all be the same length

When I pipe the generated values to a normal file ...I noticed that some row have 10values...and some rows even have 9 values..
So not all the generated rows have 11 values.
Why this happens ....how to solve ?

1. Schema (if applicable)
```{
	"type":"array",
	"length":{
		"type":"number",
		"subtype":"u64",
		"constant":10000
	},
	"content":{
		"type":"object",
		
		"special_id":{
			"optional":false,
			"type":"number",
			"subtype":"u64",
			"range":{
				"low":1,
				"high":20000,
				"step":2
			}
		},
		"first_name":{"optional":false,"type":"string","faker":{"generator":"first_name"}},
		"surname":{"optional":false,"type":"string","faker":{"generator":"last_name"}},
		"nickname":{"optional":false,"type":"string","faker":{"generator":"sentence"}},
		"ages":{
			"optional":false,
			"type":"number",
			"subtype":"u64",
			"range":{
				"low":18,
				"high":45,
				"step":1
			}			
		},
		"department":{
			"optional":false,
			"type":"string",
			"pattern": "(Accounting|Managment|IT||Sales)"
		},
		"job":{
			"optional":false,
			"type":"string",
			"faker":{
				"generator":"job"
			}
		},
		"ident":{
			"optional": true,
			"type":"string",
			"uuid":{}
		},
		"email_address":{
			"optional":false,
			"type":"string",
			"faker":{
				"generator":"company_email"
			}
		},
		"company_web":{
			"optional":true,
			"type":"string",
			"faker":{
				"generator":"safe_domain_name"
			}
		},
		"active":{
			"type":"bool",
			"frequency":0.5
		}
	}	
}

```

```

**Comment by llogiq** [comment] 2021-06-08 22:44
This might be an error in handling the optional values. We'll have a closer look tomorrow.

**Comment by beautybird** [comment] 2021-06-09 06:46
Hi,
After thorough look to the rows .. I picked 3 generated rows ...all have 10 generated values :- 

1- field  ident  in 1st row...but not in 2nd  while field comany_web not in 2nd but it's in 1st row .
2- field department  values (in 1st & 2nd rows ) are not filled with data as required by the schema ,,,,but in 3rd row yes it's filled .
 


[{"active":true,"ages":25,"department":"","email_address":"brandisalazar@diaz.com","first_name":"Aaron","ident":"0ca57b62-34bb-13f0-f6ff-78effd960655","job":"Human resources officer","nickname":"Modern relationship both successful professional.","special_id":16709,"surname":"Chaney"},

{"active":true,"ages":41,"company_web":"example.net","department":"Sales","email_address":"kristi14@marquez.biz","first_name":"Glenda","job":"Camera operator","nickname":"Successful game international among.","special_id":15059,"surname":"Kerr"},

{"active":false,"ages":23,"company_web":"example.com","department":"Managment","email_address":"benjamin86@morales-martin.com","first_name":"Robert","job":"Production manager","nickname":"Work beat until main game less.","special_id":4249,"surname":"Strickland"},

**Comment by christoshadjiaslanis** [comment] 2021-06-09 14:04
HI @beautybird - this is a bug in the Postgres integration which we'll be fixing soon.

The crux of the problem is that in JSON there is a difference between an 'optional' and 'nullable' field, whereas in most SQL databases there is no distinction.

To get around this, instead of having 'optional' you can use 'one_of' and 'null'. As an example see below:

```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "special_id": {
            "type": "number",
            "subtype": "u64",
            "range": {
                "low": 1,
                "high": 20000,
                "step": 2
            }
        },
        "first_name": {
            "type": "string",
            "faker": {
                "generator": "first_name"
            }
        },
        "surname": {
            "type": "string",
            "faker": {
                "generator": "last_name"
            }
        },
        "nickname": {
            "type": "string",
            "faker": {
                "generator": "sentence"
            }
        },
        "ages": {
            "type": "number",
            "subtype": "u64",
            "range": {
                "low": 18,
                "high": 45,
                "step": 1
            }
        },
        "department": {
            "type": "string",
            "pattern": "(Accounting|Managment|IT|Sales)"
        },
        "job": {
            "type": "string",
            "faker": {
                "generator": "job"
            }
        },
        "ident": {
            "type": "one_of",
            "variants": [
                {
                    "type": "string",
                    "uuid": {}
                },
                {
                    "weight": 1.0,
                    "type": "null"
                }
            ]
        },
        "email_address": {
            "type": "string",
            "faker": {
                "generator": "company_email"
            }
        },
        "company_web": {
            "type": "one_of",
            "variants": [
                {
                    "type": "string",
                    "faker": {
                        "generator": "safe_domain_name"
                    }
                },
                {
                    "weight": 1.0,
                    "type": "null"
                }
            ]    
        },
        "active": {
            "type": "bool",
            "frequency": 0.5
        }
    }
}
```

NB: I have modified a few things. 
1. Removed the explicit `optional: false` as it is not required (optional is false by default).
2. Replaced `optional: true` with the `one_of` and null variant. You can use the weights to tune how often you want null to appear.\
3. I have reduced the generation size constant from 10000 to 1. You can use the `--size` param to tune this: 
```bash
$ synth generate --collection test_data --size 10000 --to postgres://admin:1122@localhost:5432/data ~/db_test/data/
```

Let me know if this helps and I'll close the issue.

**Comment by beautybird** [comment] 2021-06-10 07:54
Hello @christoshadjiaslanis  
Your solution worked  ....10000 rows inserted in the DB table . 
count|
-----+
10000|

Now..  2 things I noticed though :- 
1- ident field rows not all filed with data ..does this related to your choice 
 {
                    "weight": 1.0,
                    "type": "null"
  }
2- company_web field :- 
     a- not all fields have data....also seems related to 
              {
                    "weight": 1.0,
                    "type": "null"
                }
     b - most data are duplicated (only 2 variants) ...is there a way to have more variants of the faked data .

Thank you

**Comment by christoshadjiaslanis** [comment] 2021-06-10 10:57
> ident field rows not all filed with data ..does this related to your choice

Yes. In your original schema you had them marked as `optional` so I assumed that this is the intended outcome.

> most data are duplicated (only 2 variants) ...is there a way to have more variants of the faked data .

Hmm good question. Which fields are duplicates?

**Comment by beautybird** [comment] 2021-06-10 12:34
Hi,
1- You right .
2- yes company_web ... I got it .
I appreciate your work with Synth..indeed  it's  big help for those who work with DB development.
Thank you

**Closed** 2021-06-10 13:13 UTC
Labels: bug
